"""add scopes table

Revision ID: 7f5aa372b12d
Revises: 80c12520cc5b
Create Date: 2026-09-29 02:30:24.956887

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5aa372b12d'
down_revision: Union[str, Sequence[str], None] = '80c12520cc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


scopes_table = sa.table(
    "scopes",
    sa.column("id", sa.UUID()),
    sa.column("name", sa.String()),
    sa.column("description", sa.Text()),
    sa.column("is_active", sa.Boolean()),
)

SEED_SCOPES = [
    {
        "name": "openid",
        "description": "Confirms this is an OpenID Connect request (no data by itself; reserved for future ID token support).",
    },
    {
        "name": "profile",
        "description": "Read your name and basic profile info.",
    },
    {
        "name": "email",
        "description": "Read your email address and verification status.",
    },
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scopes_name'), 'scopes', ['name'], unique=True)
    # ### end Alembic commands ###

    op.bulk_insert(
        scopes_table,
        [
            {"id": uuid.uuid4(), "is_active": True, **scope}
            for scope in SEED_SCOPES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scopes_name'), table_name='scopes')
    op.drop_table('scopes')
    # ### end Alembic commands ###
