"""add code_challenge_method to authorization_codes

Revision ID: 80c12520cc5b
Revises: 8b0e2a07267f
Create Date: 2026-09-27 17:14:50.693948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c12520cc5b'
down_revision: Union[str, Sequence[str], None] = '8b0e2a07267f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_codes', sa.Column('code_challenge_method', sa.String(length=50), server_default='S256', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization_codes', 'code_challenge_method')
    # ### end Alembic commands ###
