"""add oauth_consents table

Revision ID: 92b42340f3fb
Revises: 7008568fb5c2
Create Date: 2026-10-04 01:22:02.377299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b42340f3fb'
down_revision: Union[str, Sequence[str], None] = '7008568fb5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_oauth_consents_user_client')
    )
    op.create_index(op.f('ix_oauth_consents_client_id'), 'oauth_consents', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_consents_user_id'), 'oauth_consents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_consents_user_id'), table_name='oauth_consents')
    op.drop_index(op.f('ix_oauth_consents_client_id'), table_name='oauth_consents')
    op.drop_table('oauth_consents')
    # ### end Alembic commands ###
