"""add scope to refresh_tokens

Revision ID: 96b2331dc011
Revises: 92b42340f3fb
Create Date: 2026-10-05 23:10:02.556599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b2331dc011'
down_revision: Union[str, Sequence[str], None] = '92b42340f3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'refresh_tokens',
        sa.Column('scope', sa.Text(), nullable=False, server_default=''),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'scope')
    # ### end Alembic commands ###
