"""add allowed_scopes to oauth_clients

Revision ID: cfec7a2f8b99
Revises: 7f5aa372b12d
Create Date: 2026-09-30 01:35:31.657899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfec7a2f8b99'
down_revision: Union[str, Sequence[str], None] = '7f5aa372b12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('allowed_scopes', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'allowed_scopes')
    # ### end Alembic commands ###
